# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tweetme' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
  # Pods for tweetme

  target 'tweetme-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tweetmeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end